// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compute/ComputeMessage.proto

package com.yushijie.common.protobuf.compute;

public final class ComputeMessage {
  private ComputeMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 状态
   * </pre>
   *
   * Protobuf enum {@code one2data.rbtmqmsgcli.compute.State}
   */
  public enum State
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NO_STATE = 0;</code>
     */
    NO_STATE(0),
    /**
     * <code>RUNNING = 1;</code>
     */
    RUNNING(1),
    /**
     * <code>PAUSED = 3;</code>
     */
    PAUSED(3),
    /**
     * <code>SHUT_OFF = 5;</code>
     */
    SHUT_OFF(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NO_STATE = 0;</code>
     */
    public static final int NO_STATE_VALUE = 0;
    /**
     * <code>RUNNING = 1;</code>
     */
    public static final int RUNNING_VALUE = 1;
    /**
     * <code>PAUSED = 3;</code>
     */
    public static final int PAUSED_VALUE = 3;
    /**
     * <code>SHUT_OFF = 5;</code>
     */
    public static final int SHUT_OFF_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static State valueOf(int value) {
      return forNumber(value);
    }

    public static State forNumber(int value) {
      switch (value) {
        case 0: return NO_STATE;
        case 1: return RUNNING;
        case 3: return PAUSED;
        case 5: return SHUT_OFF;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<State>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        State> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<State>() {
            public State findValueByNumber(int number) {
              return State.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final State[] VALUES = values();

    public static State valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private State(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:one2data.rbtmqmsgcli.compute.State)
  }

  /**
   * Protobuf enum {@code one2data.rbtmqmsgcli.compute.EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 虚拟机停止
     * </pre>
     *
     * <code>STOP = 0;</code>
     */
    STOP(0),
    /**
     * <pre>
     * 虚拟机删除
     * </pre>
     *
     * <code>DELETE = 1;</code>
     */
    DELETE(1),
    /**
     * <pre>
     * 虚拟机停止并删除
     * </pre>
     *
     * <code>STOP_AND_DELETE = 2;</code>
     */
    STOP_AND_DELETE(2),
    /**
     * <pre>
     *虚拟机已完全启动
     * </pre>
     *
     * <code>START_COMPLETED = 3;</code>
     */
    START_COMPLETED(3),
    /**
     * <pre>
     *命令型事件--虚拟机启动命令执行结果-虚拟机已经执行了开机命令，通过该事件上报执行结果
     * </pre>
     *
     * <code>EXECUTE_START_RESULT = 4;</code>
     */
    EXECUTE_START_RESULT(4),
      /**
       * <pre>
       * 虚拟机快照事件
       * </pre>
       *
       * <code>SNAP_RESULT = 5;</code>
       */
      SNAP_RESULT(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 虚拟机停止
     * </pre>
     *
     * <code>STOP = 0;</code>
     */
    public static final int STOP_VALUE = 0;
    /**
     * <pre>
     * 虚拟机删除
     * </pre>
     *
     * <code>DELETE = 1;</code>
     */
    public static final int DELETE_VALUE = 1;
    /**
     * <pre>
     * 虚拟机停止并删除
     * </pre>
     *
     * <code>STOP_AND_DELETE = 2;</code>
     */
    public static final int STOP_AND_DELETE_VALUE = 2;
    /**
     * <pre>
     *虚拟机已完全启动
     * </pre>
     *
     * <code>START_COMPLETED = 3;</code>
     */
    public static final int START_COMPLETED_VALUE = 3;
    /**
     * <pre>
     *命令型事件--虚拟机启动命令执行结果-虚拟机已经执行了开机命令，通过该事件上报执行结果
     * </pre>
     *
     * <code>EXECUTE_START_RESULT = 4;</code>
     */
    public static final int EXECUTE_START_RESULT_VALUE = 4;
    /**
     * <pre>
     * 虚拟机快照事件
     * </pre>
     *
     * <code>SNAP_RESULT = 5;</code>
     */
    public static final int SNAP_RESULT_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return STOP;
        case 1: return DELETE;
        case 2: return STOP_AND_DELETE;
        case 3: return START_COMPLETED;
        case 4: return EXECUTE_START_RESULT;
        case 5:
            return SNAP_RESULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:one2data.rbtmqmsgcli.compute.EventType)
  }

  public interface InstanceEventReportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:one2data.rbtmqmsgcli.compute.InstanceEventReport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 虚拟机唯一ID
     * </pre>
     *
     * <code>optional string instance_uuid = 1;</code>
     */
    String getInstanceUuid();
    /**
     * <pre>
     * 虚拟机唯一ID
     * </pre>
     *
     * <code>optional string instance_uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getInstanceUuidBytes();

    /**
     * <pre>
     *时间戳-秒级
     * </pre>
     *
     * <code>optional int64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <pre>
     *事件类型
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.compute.EventType event_type = 3;</code>
     */
    int getEventTypeValue();
    /**
     * <pre>
     *事件类型
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.compute.EventType event_type = 3;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType getEventType();

    /**
     * <pre>
     *命令执行结果-命令型事件时使用，其他事件类型不使用
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
     */
    boolean hasCommandResult();
    /**
     * <pre>
     *命令执行结果-命令型事件时使用，其他事件类型不使用
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult getCommandResult();
    /**
     * <pre>
     *命令执行结果-命令型事件时使用，其他事件类型不使用
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResultOrBuilder getCommandResultOrBuilder();
  }
  /**
   * Protobuf type {@code one2data.rbtmqmsgcli.compute.InstanceEventReport}
   */
  public  static final class InstanceEventReport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:one2data.rbtmqmsgcli.compute.InstanceEventReport)
      InstanceEventReportOrBuilder {
    // Use InstanceEventReport.newBuilder() to construct.
    private InstanceEventReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InstanceEventReport() {
      instanceUuid_ = "";
      timestamp_ = 0L;
      eventType_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InstanceEventReport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              instanceUuid_ = s;
              break;
            }
            case 16: {

              timestamp_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              eventType_ = rawValue;
              break;
            }
            case 34: {
              cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.Builder subBuilder = null;
              if (commandResult_ != null) {
                subBuilder = commandResult_.toBuilder();
              }
              commandResult_ = input.readMessage(cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(commandResult_);
                commandResult_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReport_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport.class, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport.Builder.class);
    }

    public static final int INSTANCE_UUID_FIELD_NUMBER = 1;
    private volatile Object instanceUuid_;
    /**
     * <pre>
     * 虚拟机唯一ID
     * </pre>
     *
     * <code>optional string instance_uuid = 1;</code>
     */
    public String getInstanceUuid() {
      Object ref = instanceUuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        instanceUuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 虚拟机唯一ID
     * </pre>
     *
     * <code>optional string instance_uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInstanceUuidBytes() {
      Object ref = instanceUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        instanceUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <pre>
     *时间戳-秒级
     * </pre>
     *
     * <code>optional int64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int EVENT_TYPE_FIELD_NUMBER = 3;
    private int eventType_;
    /**
     * <pre>
     *事件类型
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.compute.EventType event_type = 3;</code>
     */
    public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <pre>
     *事件类型
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.compute.EventType event_type = 3;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType getEventType() {
      cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType result = cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType.valueOf(eventType_);
      return result == null ? cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType.UNRECOGNIZED : result;
    }

    public static final int COMMAND_RESULT_FIELD_NUMBER = 4;
    private cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult commandResult_;
    /**
     * <pre>
     *命令执行结果-命令型事件时使用，其他事件类型不使用
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
     */
    public boolean hasCommandResult() {
      return commandResult_ != null;
    }
    /**
     * <pre>
     *命令执行结果-命令型事件时使用，其他事件类型不使用
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult getCommandResult() {
      return commandResult_ == null ? cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.getDefaultInstance() : commandResult_;
    }
    /**
     * <pre>
     *命令执行结果-命令型事件时使用，其他事件类型不使用
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResultOrBuilder getCommandResultOrBuilder() {
      return getCommandResult();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getInstanceUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, instanceUuid_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (eventType_ != cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType.STOP.getNumber()) {
        output.writeEnum(3, eventType_);
      }
      if (commandResult_ != null) {
        output.writeMessage(4, getCommandResult());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getInstanceUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, instanceUuid_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (eventType_ != cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType.STOP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, eventType_);
      }
      if (commandResult_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCommandResult());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport)) {
        return super.equals(obj);
      }
      cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport other = (cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport) obj;

      boolean result = true;
      result = result && getInstanceUuid()
          .equals(other.getInstanceUuid());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && eventType_ == other.eventType_;
      result = result && (hasCommandResult() == other.hasCommandResult());
      if (hasCommandResult()) {
        result = result && getCommandResult()
            .equals(other.getCommandResult());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + INSTANCE_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getInstanceUuid().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + eventType_;
      if (hasCommandResult()) {
        hash = (37 * hash) + COMMAND_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getCommandResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code one2data.rbtmqmsgcli.compute.InstanceEventReport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:one2data.rbtmqmsgcli.compute.InstanceEventReport)
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReport_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport.class, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport.Builder.class);
      }

      // Construct using cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        instanceUuid_ = "";

        timestamp_ = 0L;

        eventType_ = 0;

        if (commandResultBuilder_ == null) {
          commandResult_ = null;
        } else {
          commandResult_ = null;
          commandResultBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReport_descriptor;
      }

      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport getDefaultInstanceForType() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport.getDefaultInstance();
      }

      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport build() {
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport buildPartial() {
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport result = new cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport(this);
        result.instanceUuid_ = instanceUuid_;
        result.timestamp_ = timestamp_;
        result.eventType_ = eventType_;
        if (commandResultBuilder_ == null) {
          result.commandResult_ = commandResult_;
        } else {
          result.commandResult_ = commandResultBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport) {
          return mergeFrom((cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport other) {
        if (other == cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport.getDefaultInstance()) return this;
        if (!other.getInstanceUuid().isEmpty()) {
          instanceUuid_ = other.instanceUuid_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.eventType_ != 0) {
          setEventTypeValue(other.getEventTypeValue());
        }
        if (other.hasCommandResult()) {
          mergeCommandResult(other.getCommandResult());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object instanceUuid_ = "";
      /**
       * <pre>
       * 虚拟机唯一ID
       * </pre>
       *
       * <code>optional string instance_uuid = 1;</code>
       */
      public String getInstanceUuid() {
        Object ref = instanceUuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          instanceUuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 虚拟机唯一ID
       * </pre>
       *
       * <code>optional string instance_uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInstanceUuidBytes() {
        Object ref = instanceUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          instanceUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 虚拟机唯一ID
       * </pre>
       *
       * <code>optional string instance_uuid = 1;</code>
       */
      public Builder setInstanceUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instanceUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 虚拟机唯一ID
       * </pre>
       *
       * <code>optional string instance_uuid = 1;</code>
       */
      public Builder clearInstanceUuid() {
        
        instanceUuid_ = getDefaultInstance().getInstanceUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 虚拟机唯一ID
       * </pre>
       *
       * <code>optional string instance_uuid = 1;</code>
       */
      public Builder setInstanceUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        instanceUuid_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <pre>
       *时间戳-秒级
       * </pre>
       *
       * <code>optional int64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <pre>
       *时间戳-秒级
       * </pre>
       *
       * <code>optional int64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳-秒级
       * </pre>
       *
       * <code>optional int64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int eventType_ = 0;
      /**
       * <pre>
       *事件类型
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.EventType event_type = 3;</code>
       */
      public int getEventTypeValue() {
        return eventType_;
      }
      /**
       * <pre>
       *事件类型
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.EventType event_type = 3;</code>
       */
      public Builder setEventTypeValue(int value) {
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *事件类型
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.EventType event_type = 3;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType getEventType() {
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType result = cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType.valueOf(eventType_);
        return result == null ? cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *事件类型
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.EventType event_type = 3;</code>
       */
      public Builder setEventType(cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        eventType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *事件类型
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.EventType event_type = 3;</code>
       */
      public Builder clearEventType() {
        
        eventType_ = 0;
        onChanged();
        return this;
      }

      private cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult commandResult_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.Builder, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResultOrBuilder> commandResultBuilder_;
      /**
       * <pre>
       *命令执行结果-命令型事件时使用，其他事件类型不使用
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
       */
      public boolean hasCommandResult() {
        return commandResultBuilder_ != null || commandResult_ != null;
      }
      /**
       * <pre>
       *命令执行结果-命令型事件时使用，其他事件类型不使用
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult getCommandResult() {
        if (commandResultBuilder_ == null) {
          return commandResult_ == null ? cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.getDefaultInstance() : commandResult_;
        } else {
          return commandResultBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *命令执行结果-命令型事件时使用，其他事件类型不使用
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
       */
      public Builder setCommandResult(cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult value) {
        if (commandResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          commandResult_ = value;
          onChanged();
        } else {
          commandResultBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *命令执行结果-命令型事件时使用，其他事件类型不使用
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
       */
      public Builder setCommandResult(
          cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.Builder builderForValue) {
        if (commandResultBuilder_ == null) {
          commandResult_ = builderForValue.build();
          onChanged();
        } else {
          commandResultBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *命令执行结果-命令型事件时使用，其他事件类型不使用
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
       */
      public Builder mergeCommandResult(cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult value) {
        if (commandResultBuilder_ == null) {
          if (commandResult_ != null) {
            commandResult_ =
              cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.newBuilder(commandResult_).mergeFrom(value).buildPartial();
          } else {
            commandResult_ = value;
          }
          onChanged();
        } else {
          commandResultBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *命令执行结果-命令型事件时使用，其他事件类型不使用
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
       */
      public Builder clearCommandResult() {
        if (commandResultBuilder_ == null) {
          commandResult_ = null;
          onChanged();
        } else {
          commandResult_ = null;
          commandResultBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *命令执行结果-命令型事件时使用，其他事件类型不使用
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.Builder getCommandResultBuilder() {
        
        onChanged();
        return getCommandResultFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *命令执行结果-命令型事件时使用，其他事件类型不使用
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResultOrBuilder getCommandResultOrBuilder() {
        if (commandResultBuilder_ != null) {
          return commandResultBuilder_.getMessageOrBuilder();
        } else {
          return commandResult_ == null ?
              cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.getDefaultInstance() : commandResult_;
        }
      }
      /**
       * <pre>
       *命令执行结果-命令型事件时使用，其他事件类型不使用
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.compute.CommandResult command_result = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.Builder, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResultOrBuilder> 
          getCommandResultFieldBuilder() {
        if (commandResultBuilder_ == null) {
          commandResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.Builder, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResultOrBuilder>(
                  getCommandResult(),
                  getParentForChildren(),
                  isClean());
          commandResult_ = null;
        }
        return commandResultBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:one2data.rbtmqmsgcli.compute.InstanceEventReport)
    }

    // @@protoc_insertion_point(class_scope:one2data.rbtmqmsgcli.compute.InstanceEventReport)
    private static final cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport();
    }

    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstanceEventReport>
        PARSER = new com.google.protobuf.AbstractParser<InstanceEventReport>() {
      public InstanceEventReport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InstanceEventReport(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InstanceEventReport> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InstanceEventReport> getParserForType() {
      return PARSER;
    }

    public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CommandResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:one2data.rbtmqmsgcli.compute.CommandResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *响应码
     * </pre>
     *
     * <code>optional uint32 code = 1;</code>
     */
    int getCode();

    /**
     * <pre>
     *响应信息
     * </pre>
     *
     * <code>optional string msg = 2;</code>
     */
    String getMsg();
    /**
     * <pre>
     *响应信息
     * </pre>
     *
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code one2data.rbtmqmsgcli.compute.CommandResult}
   */
  public  static final class CommandResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:one2data.rbtmqmsgcli.compute.CommandResult)
      CommandResultOrBuilder {
    // Use CommandResult.newBuilder() to construct.
    private CommandResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommandResult() {
      code_ = 0;
      msg_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CommandResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              code_ = input.readUInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_CommandResult_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_CommandResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.class, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     *响应码
     * </pre>
     *
     * <code>optional uint32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile Object msg_;
    /**
     * <pre>
     *响应信息
     * </pre>
     *
     * <code>optional string msg = 2;</code>
     */
    public String getMsg() {
      Object ref = msg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *响应信息
     * </pre>
     *
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      Object ref = msg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeUInt32(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult)) {
        return super.equals(obj);
      }
      cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult other = (cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult) obj;

      boolean result = true;
      result = result && (getCode()
          == other.getCode());
      result = result && getMsg()
          .equals(other.getMsg());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code one2data.rbtmqmsgcli.compute.CommandResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:one2data.rbtmqmsgcli.compute.CommandResult)
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_CommandResult_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_CommandResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.class, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.Builder.class);
      }

      // Construct using cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 0;

        msg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_CommandResult_descriptor;
      }

      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult getDefaultInstanceForType() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.getDefaultInstance();
      }

      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult build() {
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult buildPartial() {
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult result = new cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult(this);
        result.code_ = code_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult) {
          return mergeFrom((cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult other) {
        if (other == cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       *响应码
       * </pre>
       *
       * <code>optional uint32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       *响应码
       * </pre>
       *
       * <code>optional uint32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *响应码
       * </pre>
       *
       * <code>optional uint32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private Object msg_ = "";
      /**
       * <pre>
       *响应信息
       * </pre>
       *
       * <code>optional string msg = 2;</code>
       */
      public String getMsg() {
        Object ref = msg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *响应信息
       * </pre>
       *
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *响应信息
       * </pre>
       *
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *响应信息
       * </pre>
       *
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *响应信息
       * </pre>
       *
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:one2data.rbtmqmsgcli.compute.CommandResult)
    }

    // @@protoc_insertion_point(class_scope:one2data.rbtmqmsgcli.compute.CommandResult)
    private static final cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult();
    }

    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommandResult>
        PARSER = new com.google.protobuf.AbstractParser<CommandResult>() {
      public CommandResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CommandResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommandResult> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CommandResult> getParserForType() {
      return PARSER;
    }

    public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.CommandResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InstanceEventReportAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:one2data.rbtmqmsgcli.compute.InstanceEventReportAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * ack
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    boolean hasBaseAck();
    /**
     * <pre>
     * ack
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck getBaseAck();
    /**
     * <pre>
     * ack
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder getBaseAckOrBuilder();
  }
  /**
   * Protobuf type {@code one2data.rbtmqmsgcli.compute.InstanceEventReportAck}
   */
  public  static final class InstanceEventReportAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:one2data.rbtmqmsgcli.compute.InstanceEventReportAck)
      InstanceEventReportAckOrBuilder {
    // Use InstanceEventReportAck.newBuilder() to construct.
    private InstanceEventReportAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InstanceEventReportAck() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InstanceEventReportAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder subBuilder = null;
              if (baseAck_ != null) {
                subBuilder = baseAck_.toBuilder();
              }
              baseAck_ = input.readMessage(cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseAck_);
                baseAck_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReportAck_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReportAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck.class, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck.Builder.class);
    }

    public static final int BASE_ACK_FIELD_NUMBER = 1;
    private cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck baseAck_;
    /**
     * <pre>
     * ack
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    public boolean hasBaseAck() {
      return baseAck_ != null;
    }
    /**
     * <pre>
     * ack
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck getBaseAck() {
      return baseAck_ == null ? cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.getDefaultInstance() : baseAck_;
    }
    /**
     * <pre>
     * ack
     * </pre>
     *
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder getBaseAckOrBuilder() {
      return getBaseAck();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseAck_ != null) {
        output.writeMessage(1, getBaseAck());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseAck_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseAck());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck)) {
        return super.equals(obj);
      }
      cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck other = (cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck) obj;

      boolean result = true;
      result = result && (hasBaseAck() == other.hasBaseAck());
      if (hasBaseAck()) {
        result = result && getBaseAck()
            .equals(other.getBaseAck());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBaseAck()) {
        hash = (37 * hash) + BASE_ACK_FIELD_NUMBER;
        hash = (53 * hash) + getBaseAck().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code one2data.rbtmqmsgcli.compute.InstanceEventReportAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:one2data.rbtmqmsgcli.compute.InstanceEventReportAck)
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReportAck_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReportAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck.class, cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck.Builder.class);
      }

      // Construct using cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (baseAckBuilder_ == null) {
          baseAck_ = null;
        } else {
          baseAck_ = null;
          baseAckBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReportAck_descriptor;
      }

      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck getDefaultInstanceForType() {
        return cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck.getDefaultInstance();
      }

      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck build() {
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck buildPartial() {
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck result = new cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck(this);
        if (baseAckBuilder_ == null) {
          result.baseAck_ = baseAck_;
        } else {
          result.baseAck_ = baseAckBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck) {
          return mergeFrom((cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck other) {
        if (other == cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck.getDefaultInstance()) return this;
        if (other.hasBaseAck()) {
          mergeBaseAck(other.getBaseAck());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck baseAck_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder> baseAckBuilder_;
      /**
       * <pre>
       * ack
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public boolean hasBaseAck() {
        return baseAckBuilder_ != null || baseAck_ != null;
      }
      /**
       * <pre>
       * ack
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck getBaseAck() {
        if (baseAckBuilder_ == null) {
          return baseAck_ == null ? cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.getDefaultInstance() : baseAck_;
        } else {
          return baseAckBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * ack
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public Builder setBaseAck(cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck value) {
        if (baseAckBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseAck_ = value;
          onChanged();
        } else {
          baseAckBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * ack
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public Builder setBaseAck(
          cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder builderForValue) {
        if (baseAckBuilder_ == null) {
          baseAck_ = builderForValue.build();
          onChanged();
        } else {
          baseAckBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * ack
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public Builder mergeBaseAck(cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck value) {
        if (baseAckBuilder_ == null) {
          if (baseAck_ != null) {
            baseAck_ =
              cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.newBuilder(baseAck_).mergeFrom(value).buildPartial();
          } else {
            baseAck_ = value;
          }
          onChanged();
        } else {
          baseAckBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * ack
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public Builder clearBaseAck() {
        if (baseAckBuilder_ == null) {
          baseAck_ = null;
          onChanged();
        } else {
          baseAck_ = null;
          baseAckBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * ack
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder getBaseAckBuilder() {
        
        onChanged();
        return getBaseAckFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * ack
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder getBaseAckOrBuilder() {
        if (baseAckBuilder_ != null) {
          return baseAckBuilder_.getMessageOrBuilder();
        } else {
          return baseAck_ == null ?
              cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.getDefaultInstance() : baseAck_;
        }
      }
      /**
       * <pre>
       * ack
       * </pre>
       *
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder> 
          getBaseAckFieldBuilder() {
        if (baseAckBuilder_ == null) {
          baseAckBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder>(
                  getBaseAck(),
                  getParentForChildren(),
                  isClean());
          baseAck_ = null;
        }
        return baseAckBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:one2data.rbtmqmsgcli.compute.InstanceEventReportAck)
    }

    // @@protoc_insertion_point(class_scope:one2data.rbtmqmsgcli.compute.InstanceEventReportAck)
    private static final cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck();
    }

    public static cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstanceEventReportAck>
        PARSER = new com.google.protobuf.AbstractParser<InstanceEventReportAck>() {
      public InstanceEventReportAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InstanceEventReportAck(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InstanceEventReportAck> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InstanceEventReportAck> getParserForType() {
      return PARSER;
    }

    public cn.keptdata.one2data.header.message.protobuf.compute.ComputeMessage.InstanceEventReportAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReport_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_one2data_rbtmqmsgcli_compute_CommandResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_one2data_rbtmqmsgcli_compute_CommandResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReportAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReportAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034compute/ComputeMessage.proto\022\034one2data" +
      ".rbtmqmsgcli.compute\032\023common/Common.prot" +
      "o\"\301\001\n\023InstanceEventReport\022\025\n\rinstance_uu" +
      "id\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\003\022;\n\nevent_typ" +
      "e\030\003 \001(\0162\'.one2data.rbtmqmsgcli.compute.E" +
      "ventType\022C\n\016command_result\030\004 \001(\0132+.one2d" +
      "ata.rbtmqmsgcli.compute.CommandResult\"*\n" +
      "\rCommandResult\022\014\n\004code\030\001 \001(\r\022\013\n\003msg\030\002 \001(" +
      "\t\"P\n\026InstanceEventReportAck\0226\n\010base_ack\030" +
      "\001 \001(\0132$.one2data.rbtmqmsgcli.common.Base",
      "Ack*<\n\005State\022\014\n\010NO_STATE\020\000\022\013\n\007RUNNING\020\001\022" +
            "\n\n\006PAUSED\020\003\022\014\n\010SHUT_OFF\020\005*v\n\tEventType\022\010"
            +
      "\n\004STOP\020\000\022\n\n\006DELETE\020\001\022\023\n\017STOP_AND_DELETE\020" +
      "\002\022\023\n\017START_COMPLETED\020\003\022\030\n\024EXECUTE_START_" +
            "RESULT\020\004\022\017\n\013SNAP_RESULT\020\005BF\n4cn.keptdata"
            + ".one2data.header.message.protobuf.comput" + "eB\016ComputeMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.keptdata.one2data.header.message.protobuf.common.Common.getDescriptor(),
        }, assigner);
    internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReport_descriptor,
        new String[] { "InstanceUuid", "Timestamp", "EventType", "CommandResult", });
    internal_static_one2data_rbtmqmsgcli_compute_CommandResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_one2data_rbtmqmsgcli_compute_CommandResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_one2data_rbtmqmsgcli_compute_CommandResult_descriptor,
        new String[] { "Code", "Msg", });
    internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReportAck_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReportAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_one2data_rbtmqmsgcli_compute_InstanceEventReportAck_descriptor,
        new String[] { "BaseAck", });
    cn.keptdata.one2data.header.message.protobuf.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
