// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage/ControlMulti.proto

package com.yushijie.common.protobuf.storage;

public final class ControlMulti {
  private ControlMulti() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MultiCreateRelayAndAppQcow2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:one2data.rbtmqmsgcli.control.MultiCreateRelayAndAppQcow2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 批量任务唯一ID
     * </pre>
     *
     * <code>optional string job_uuid = 1;</code>
     */
    String getJobUuid();
    /**
     * <pre>
     * 批量任务唯一ID
     * </pre>
     *
     * <code>optional string job_uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getJobUuidBytes();

    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
     */
    java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2> 
        getBatchList();
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2 getBatch(int index);
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
     */
    int getBatchCount();
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
     */
    java.util.List<? extends cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2OrBuilder> 
        getBatchOrBuilderList();
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2OrBuilder getBatchOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code one2data.rbtmqmsgcli.control.MultiCreateRelayAndAppQcow2}
   */
  public  static final class MultiCreateRelayAndAppQcow2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:one2data.rbtmqmsgcli.control.MultiCreateRelayAndAppQcow2)
      MultiCreateRelayAndAppQcow2OrBuilder {
    // Use MultiCreateRelayAndAppQcow2.newBuilder() to construct.
    private MultiCreateRelayAndAppQcow2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultiCreateRelayAndAppQcow2() {
      jobUuid_ = "";
      batch_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MultiCreateRelayAndAppQcow2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              jobUuid_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                batch_ = new java.util.ArrayList<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2>();
                mutable_bitField0_ |= 0x00000002;
              }
              batch_.add(
                  input.readMessage(cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          batch_ = java.util.Collections.unmodifiableList(batch_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.internal_static_one2data_rbtmqmsgcli_control_MultiCreateRelayAndAppQcow2_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.internal_static_one2data_rbtmqmsgcli_control_MultiCreateRelayAndAppQcow2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2.class, cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2.Builder.class);
    }

    private int bitField0_;
    public static final int JOB_UUID_FIELD_NUMBER = 1;
    private volatile Object jobUuid_;
    /**
     * <pre>
     * 批量任务唯一ID
     * </pre>
     *
     * <code>optional string job_uuid = 1;</code>
     */
    public String getJobUuid() {
      Object ref = jobUuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        jobUuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 批量任务唯一ID
     * </pre>
     *
     * <code>optional string job_uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJobUuidBytes() {
      Object ref = jobUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        jobUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BATCH_FIELD_NUMBER = 2;
    private java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2> batch_;
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
     */
    public java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2> getBatchList() {
      return batch_;
    }
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
     */
    public java.util.List<? extends cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2OrBuilder> 
        getBatchOrBuilderList() {
      return batch_;
    }
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
     */
    public int getBatchCount() {
      return batch_.size();
    }
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2 getBatch(int index) {
      return batch_.get(index);
    }
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2OrBuilder getBatchOrBuilder(
        int index) {
      return batch_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getJobUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jobUuid_);
      }
      for (int i = 0; i < batch_.size(); i++) {
        output.writeMessage(2, batch_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getJobUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jobUuid_);
      }
      for (int i = 0; i < batch_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, batch_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2)) {
        return super.equals(obj);
      }
      cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 other = (cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2) obj;

      boolean result = true;
      result = result && getJobUuid()
          .equals(other.getJobUuid());
      result = result && getBatchList()
          .equals(other.getBatchList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + JOB_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getJobUuid().hashCode();
      if (getBatchCount() > 0) {
        hash = (37 * hash) + BATCH_FIELD_NUMBER;
        hash = (53 * hash) + getBatchList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code one2data.rbtmqmsgcli.control.MultiCreateRelayAndAppQcow2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:one2data.rbtmqmsgcli.control.MultiCreateRelayAndAppQcow2)
        cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.internal_static_one2data_rbtmqmsgcli_control_MultiCreateRelayAndAppQcow2_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.internal_static_one2data_rbtmqmsgcli_control_MultiCreateRelayAndAppQcow2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2.class, cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2.Builder.class);
      }

      // Construct using cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBatchFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        jobUuid_ = "";

        if (batchBuilder_ == null) {
          batch_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          batchBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.internal_static_one2data_rbtmqmsgcli_control_MultiCreateRelayAndAppQcow2_descriptor;
      }

      public cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 getDefaultInstanceForType() {
        return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2.getDefaultInstance();
      }

      public cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 build() {
        cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 buildPartial() {
        cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 result = new cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.jobUuid_ = jobUuid_;
        if (batchBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            batch_ = java.util.Collections.unmodifiableList(batch_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.batch_ = batch_;
        } else {
          result.batch_ = batchBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2) {
          return mergeFrom((cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 other) {
        if (other == cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2.getDefaultInstance()) return this;
        if (!other.getJobUuid().isEmpty()) {
          jobUuid_ = other.jobUuid_;
          onChanged();
        }
        if (batchBuilder_ == null) {
          if (!other.batch_.isEmpty()) {
            if (batch_.isEmpty()) {
              batch_ = other.batch_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBatchIsMutable();
              batch_.addAll(other.batch_);
            }
            onChanged();
          }
        } else {
          if (!other.batch_.isEmpty()) {
            if (batchBuilder_.isEmpty()) {
              batchBuilder_.dispose();
              batchBuilder_ = null;
              batch_ = other.batch_;
              bitField0_ = (bitField0_ & ~0x00000002);
              batchBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBatchFieldBuilder() : null;
            } else {
              batchBuilder_.addAllMessages(other.batch_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object jobUuid_ = "";
      /**
       * <pre>
       * 批量任务唯一ID
       * </pre>
       *
       * <code>optional string job_uuid = 1;</code>
       */
      public String getJobUuid() {
        Object ref = jobUuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          jobUuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 批量任务唯一ID
       * </pre>
       *
       * <code>optional string job_uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJobUuidBytes() {
        Object ref = jobUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          jobUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 批量任务唯一ID
       * </pre>
       *
       * <code>optional string job_uuid = 1;</code>
       */
      public Builder setJobUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jobUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 批量任务唯一ID
       * </pre>
       *
       * <code>optional string job_uuid = 1;</code>
       */
      public Builder clearJobUuid() {
        
        jobUuid_ = getDefaultInstance().getJobUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 批量任务唯一ID
       * </pre>
       *
       * <code>optional string job_uuid = 1;</code>
       */
      public Builder setJobUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jobUuid_ = value;
        onChanged();
        return this;
      }

      private java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2> batch_ =
        java.util.Collections.emptyList();
      private void ensureBatchIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          batch_ = new java.util.ArrayList<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2>(batch_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.Builder, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2OrBuilder> batchBuilder_;

      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2> getBatchList() {
        if (batchBuilder_ == null) {
          return java.util.Collections.unmodifiableList(batch_);
        } else {
          return batchBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public int getBatchCount() {
        if (batchBuilder_ == null) {
          return batch_.size();
        } else {
          return batchBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2 getBatch(int index) {
        if (batchBuilder_ == null) {
          return batch_.get(index);
        } else {
          return batchBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public Builder setBatch(
          int index, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2 value) {
        if (batchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchIsMutable();
          batch_.set(index, value);
          onChanged();
        } else {
          batchBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public Builder setBatch(
          int index, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.Builder builderForValue) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.set(index, builderForValue.build());
          onChanged();
        } else {
          batchBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public Builder addBatch(cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2 value) {
        if (batchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchIsMutable();
          batch_.add(value);
          onChanged();
        } else {
          batchBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public Builder addBatch(
          int index, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2 value) {
        if (batchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchIsMutable();
          batch_.add(index, value);
          onChanged();
        } else {
          batchBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public Builder addBatch(
          cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.Builder builderForValue) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.add(builderForValue.build());
          onChanged();
        } else {
          batchBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public Builder addBatch(
          int index, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.Builder builderForValue) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.add(index, builderForValue.build());
          onChanged();
        } else {
          batchBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public Builder addAllBatch(
          Iterable<? extends cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2> values) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, batch_);
          onChanged();
        } else {
          batchBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public Builder clearBatch() {
        if (batchBuilder_ == null) {
          batch_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          batchBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public Builder removeBatch(int index) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.remove(index);
          onChanged();
        } else {
          batchBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.Builder getBatchBuilder(
          int index) {
        return getBatchFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2OrBuilder getBatchOrBuilder(
          int index) {
        if (batchBuilder_ == null) {
          return batch_.get(index);  } else {
          return batchBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public java.util.List<? extends cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2OrBuilder> 
           getBatchOrBuilderList() {
        if (batchBuilder_ != null) {
          return batchBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(batch_);
        }
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.Builder addBatchBuilder() {
        return getBatchFieldBuilder().addBuilder(
            cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.getDefaultInstance());
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.Builder addBatchBuilder(
          int index) {
        return getBatchFieldBuilder().addBuilder(
            index, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.getDefaultInstance());
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateRelayAndAppQcow2 batch = 2;</code>
       */
      public java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.Builder> 
           getBatchBuilderList() {
        return getBatchFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.Builder, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2OrBuilder> 
          getBatchFieldBuilder() {
        if (batchBuilder_ == null) {
          batchBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2.Builder, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateRelayAndAppQcow2OrBuilder>(
                  batch_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          batch_ = null;
        }
        return batchBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:one2data.rbtmqmsgcli.control.MultiCreateRelayAndAppQcow2)
    }

    // @@protoc_insertion_point(class_scope:one2data.rbtmqmsgcli.control.MultiCreateRelayAndAppQcow2)
    private static final cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2();
    }

    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultiCreateRelayAndAppQcow2>
        PARSER = new com.google.protobuf.AbstractParser<MultiCreateRelayAndAppQcow2>() {
      public MultiCreateRelayAndAppQcow2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MultiCreateRelayAndAppQcow2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultiCreateRelayAndAppQcow2> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MultiCreateRelayAndAppQcow2> getParserForType() {
      return PARSER;
    }

    public cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateRelayAndAppQcow2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MultiCreateAppQcow2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:one2data.rbtmqmsgcli.control.MultiCreateAppQcow2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 批量任务唯一ID
     * </pre>
     *
     * <code>optional string job_uuid = 1;</code>
     */
    String getJobUuid();
    /**
     * <pre>
     * 批量任务唯一ID
     * </pre>
     *
     * <code>optional string job_uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getJobUuidBytes();

    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
     */
    java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2> 
        getBatchList();
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2 getBatch(int index);
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
     */
    int getBatchCount();
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
     */
    java.util.List<? extends cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2OrBuilder> 
        getBatchOrBuilderList();
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2OrBuilder getBatchOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code one2data.rbtmqmsgcli.control.MultiCreateAppQcow2}
   */
  public  static final class MultiCreateAppQcow2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:one2data.rbtmqmsgcli.control.MultiCreateAppQcow2)
      MultiCreateAppQcow2OrBuilder {
    // Use MultiCreateAppQcow2.newBuilder() to construct.
    private MultiCreateAppQcow2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MultiCreateAppQcow2() {
      jobUuid_ = "";
      batch_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MultiCreateAppQcow2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              jobUuid_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                batch_ = new java.util.ArrayList<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2>();
                mutable_bitField0_ |= 0x00000002;
              }
              batch_.add(
                  input.readMessage(cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          batch_ = java.util.Collections.unmodifiableList(batch_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.internal_static_one2data_rbtmqmsgcli_control_MultiCreateAppQcow2_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.internal_static_one2data_rbtmqmsgcli_control_MultiCreateAppQcow2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2.class, cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2.Builder.class);
    }

    private int bitField0_;
    public static final int JOB_UUID_FIELD_NUMBER = 1;
    private volatile Object jobUuid_;
    /**
     * <pre>
     * 批量任务唯一ID
     * </pre>
     *
     * <code>optional string job_uuid = 1;</code>
     */
    public String getJobUuid() {
      Object ref = jobUuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        jobUuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 批量任务唯一ID
     * </pre>
     *
     * <code>optional string job_uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJobUuidBytes() {
      Object ref = jobUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        jobUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BATCH_FIELD_NUMBER = 2;
    private java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2> batch_;
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
     */
    public java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2> getBatchList() {
      return batch_;
    }
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
     */
    public java.util.List<? extends cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2OrBuilder> 
        getBatchOrBuilderList() {
      return batch_;
    }
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
     */
    public int getBatchCount() {
      return batch_.size();
    }
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2 getBatch(int index) {
      return batch_.get(index);
    }
    /**
     * <pre>
     * 多批量
     * </pre>
     *
     * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2OrBuilder getBatchOrBuilder(
        int index) {
      return batch_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getJobUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jobUuid_);
      }
      for (int i = 0; i < batch_.size(); i++) {
        output.writeMessage(2, batch_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getJobUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jobUuid_);
      }
      for (int i = 0; i < batch_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, batch_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2)) {
        return super.equals(obj);
      }
      cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 other = (cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2) obj;

      boolean result = true;
      result = result && getJobUuid()
          .equals(other.getJobUuid());
      result = result && getBatchList()
          .equals(other.getBatchList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + JOB_UUID_FIELD_NUMBER;
      hash = (53 * hash) + getJobUuid().hashCode();
      if (getBatchCount() > 0) {
        hash = (37 * hash) + BATCH_FIELD_NUMBER;
        hash = (53 * hash) + getBatchList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code one2data.rbtmqmsgcli.control.MultiCreateAppQcow2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:one2data.rbtmqmsgcli.control.MultiCreateAppQcow2)
        cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.internal_static_one2data_rbtmqmsgcli_control_MultiCreateAppQcow2_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.internal_static_one2data_rbtmqmsgcli_control_MultiCreateAppQcow2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2.class, cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2.Builder.class);
      }

      // Construct using cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBatchFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        jobUuid_ = "";

        if (batchBuilder_ == null) {
          batch_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          batchBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.internal_static_one2data_rbtmqmsgcli_control_MultiCreateAppQcow2_descriptor;
      }

      public cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 getDefaultInstanceForType() {
        return cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2.getDefaultInstance();
      }

      public cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 build() {
        cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 buildPartial() {
        cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 result = new cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.jobUuid_ = jobUuid_;
        if (batchBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            batch_ = java.util.Collections.unmodifiableList(batch_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.batch_ = batch_;
        } else {
          result.batch_ = batchBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2) {
          return mergeFrom((cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 other) {
        if (other == cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2.getDefaultInstance()) return this;
        if (!other.getJobUuid().isEmpty()) {
          jobUuid_ = other.jobUuid_;
          onChanged();
        }
        if (batchBuilder_ == null) {
          if (!other.batch_.isEmpty()) {
            if (batch_.isEmpty()) {
              batch_ = other.batch_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBatchIsMutable();
              batch_.addAll(other.batch_);
            }
            onChanged();
          }
        } else {
          if (!other.batch_.isEmpty()) {
            if (batchBuilder_.isEmpty()) {
              batchBuilder_.dispose();
              batchBuilder_ = null;
              batch_ = other.batch_;
              bitField0_ = (bitField0_ & ~0x00000002);
              batchBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBatchFieldBuilder() : null;
            } else {
              batchBuilder_.addAllMessages(other.batch_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object jobUuid_ = "";
      /**
       * <pre>
       * 批量任务唯一ID
       * </pre>
       *
       * <code>optional string job_uuid = 1;</code>
       */
      public String getJobUuid() {
        Object ref = jobUuid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          jobUuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 批量任务唯一ID
       * </pre>
       *
       * <code>optional string job_uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJobUuidBytes() {
        Object ref = jobUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          jobUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 批量任务唯一ID
       * </pre>
       *
       * <code>optional string job_uuid = 1;</code>
       */
      public Builder setJobUuid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        jobUuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 批量任务唯一ID
       * </pre>
       *
       * <code>optional string job_uuid = 1;</code>
       */
      public Builder clearJobUuid() {
        
        jobUuid_ = getDefaultInstance().getJobUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 批量任务唯一ID
       * </pre>
       *
       * <code>optional string job_uuid = 1;</code>
       */
      public Builder setJobUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        jobUuid_ = value;
        onChanged();
        return this;
      }

      private java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2> batch_ =
        java.util.Collections.emptyList();
      private void ensureBatchIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          batch_ = new java.util.ArrayList<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2>(batch_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.Builder, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2OrBuilder> batchBuilder_;

      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2> getBatchList() {
        if (batchBuilder_ == null) {
          return java.util.Collections.unmodifiableList(batch_);
        } else {
          return batchBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public int getBatchCount() {
        if (batchBuilder_ == null) {
          return batch_.size();
        } else {
          return batchBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2 getBatch(int index) {
        if (batchBuilder_ == null) {
          return batch_.get(index);
        } else {
          return batchBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public Builder setBatch(
          int index, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2 value) {
        if (batchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchIsMutable();
          batch_.set(index, value);
          onChanged();
        } else {
          batchBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public Builder setBatch(
          int index, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.Builder builderForValue) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.set(index, builderForValue.build());
          onChanged();
        } else {
          batchBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public Builder addBatch(cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2 value) {
        if (batchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchIsMutable();
          batch_.add(value);
          onChanged();
        } else {
          batchBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public Builder addBatch(
          int index, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2 value) {
        if (batchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBatchIsMutable();
          batch_.add(index, value);
          onChanged();
        } else {
          batchBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public Builder addBatch(
          cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.Builder builderForValue) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.add(builderForValue.build());
          onChanged();
        } else {
          batchBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public Builder addBatch(
          int index, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.Builder builderForValue) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.add(index, builderForValue.build());
          onChanged();
        } else {
          batchBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public Builder addAllBatch(
          Iterable<? extends cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2> values) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, batch_);
          onChanged();
        } else {
          batchBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public Builder clearBatch() {
        if (batchBuilder_ == null) {
          batch_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          batchBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public Builder removeBatch(int index) {
        if (batchBuilder_ == null) {
          ensureBatchIsMutable();
          batch_.remove(index);
          onChanged();
        } else {
          batchBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.Builder getBatchBuilder(
          int index) {
        return getBatchFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2OrBuilder getBatchOrBuilder(
          int index) {
        if (batchBuilder_ == null) {
          return batch_.get(index);  } else {
          return batchBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public java.util.List<? extends cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2OrBuilder> 
           getBatchOrBuilderList() {
        if (batchBuilder_ != null) {
          return batchBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(batch_);
        }
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.Builder addBatchBuilder() {
        return getBatchFieldBuilder().addBuilder(
            cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.getDefaultInstance());
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.Builder addBatchBuilder(
          int index) {
        return getBatchFieldBuilder().addBuilder(
            index, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.getDefaultInstance());
      }
      /**
       * <pre>
       * 多批量
       * </pre>
       *
       * <code>repeated .one2data.rbtmqmsgcli.control.BatchCreateAppQcow2 batch = 2;</code>
       */
      public java.util.List<cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.Builder> 
           getBatchBuilderList() {
        return getBatchFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.Builder, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2OrBuilder> 
          getBatchFieldBuilder() {
        if (batchBuilder_ == null) {
          batchBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2.Builder, cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.BatchCreateAppQcow2OrBuilder>(
                  batch_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          batch_ = null;
        }
        return batchBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:one2data.rbtmqmsgcli.control.MultiCreateAppQcow2)
    }

    // @@protoc_insertion_point(class_scope:one2data.rbtmqmsgcli.control.MultiCreateAppQcow2)
    private static final cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2();
    }

    public static cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MultiCreateAppQcow2>
        PARSER = new com.google.protobuf.AbstractParser<MultiCreateAppQcow2>() {
      public MultiCreateAppQcow2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MultiCreateAppQcow2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MultiCreateAppQcow2> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MultiCreateAppQcow2> getParserForType() {
      return PARSER;
    }

    public cn.keptdata.one2data.header.message.protobuf.storage.ControlMulti.MultiCreateAppQcow2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_one2data_rbtmqmsgcli_control_MultiCreateRelayAndAppQcow2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_one2data_rbtmqmsgcli_control_MultiCreateRelayAndAppQcow2_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_one2data_rbtmqmsgcli_control_MultiCreateAppQcow2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_one2data_rbtmqmsgcli_control_MultiCreateAppQcow2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032storage/ControlMulti.proto\022\034one2data.r" +
      "btmqmsgcli.control\032\023common/Common.proto\032" +
      "\033storage/ControlAction.proto\032\032storage/Co" +
      "ntrolBatch.proto\"y\n\033MultiCreateRelayAndA" +
      "ppQcow2\022\020\n\010job_uuid\030\001 \001(\t\022H\n\005batch\030\002 \003(\013" +
      "29.one2data.rbtmqmsgcli.control.BatchCre" +
      "ateRelayAndAppQcow2\"i\n\023MultiCreateAppQco" +
      "w2\022\020\n\010job_uuid\030\001 \001(\t\022@\n\005batch\030\002 \003(\01321.on" +
      "e2data.rbtmqmsgcli.control.BatchCreateAp" +
      "pQcow2BD\n4cn.keptdata.one2data.header.me",
      "ssage.protobuf.storageB\014ControlMultib\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.keptdata.one2data.header.message.protobuf.common.Common.getDescriptor(),
          cn.keptdata.one2data.header.message.protobuf.storage.ControlAction.getDescriptor(),
          cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.getDescriptor(),
        }, assigner);
    internal_static_one2data_rbtmqmsgcli_control_MultiCreateRelayAndAppQcow2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_one2data_rbtmqmsgcli_control_MultiCreateRelayAndAppQcow2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_one2data_rbtmqmsgcli_control_MultiCreateRelayAndAppQcow2_descriptor,
        new String[] { "JobUuid", "Batch", });
    internal_static_one2data_rbtmqmsgcli_control_MultiCreateAppQcow2_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_one2data_rbtmqmsgcli_control_MultiCreateAppQcow2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_one2data_rbtmqmsgcli_control_MultiCreateAppQcow2_descriptor,
        new String[] { "JobUuid", "Batch", });
    cn.keptdata.one2data.header.message.protobuf.common.Common.getDescriptor();
    cn.keptdata.one2data.header.message.protobuf.storage.ControlAction.getDescriptor();
    cn.keptdata.one2data.header.message.protobuf.storage.ControlBatch.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
