// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: initiator/InitiatorMessage.proto

package com.yushijie.common.protobuf.initiator;

public final class InitiatorMessage {
  private InitiatorMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReportNodeInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:one2data.rbtmqmsgcli.initiator.ReportNodeInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
     */
    boolean hasInitiatorInfo();
    /**
     * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo getInitiatorInfo();
    /**
     * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfoOrBuilder getInitiatorInfoOrBuilder();

    /**
     * <code>optional string binding_key = 2;</code>
     */
    String getBindingKey();
    /**
     * <code>optional string binding_key = 2;</code>
     */
    com.google.protobuf.ByteString
        getBindingKeyBytes();

    /**
     * <code>optional string filebrowser_version = 3;</code>
     */
    String getFilebrowserVersion();
    /**
     * <code>optional string filebrowser_version = 3;</code>
     */
    com.google.protobuf.ByteString
        getFilebrowserVersionBytes();
  }
  /**
   * <pre>
   * 上报Initiator信息
   * </pre>
   *
   * Protobuf type {@code one2data.rbtmqmsgcli.initiator.ReportNodeInfo}
   */
  public  static final class ReportNodeInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:one2data.rbtmqmsgcli.initiator.ReportNodeInfo)
      ReportNodeInfoOrBuilder {
    // Use ReportNodeInfo.newBuilder() to construct.
    private ReportNodeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReportNodeInfo() {
      bindingKey_ = "";
      filebrowserVersion_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ReportNodeInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo.Builder subBuilder = null;
              if (initiatorInfo_ != null) {
                subBuilder = initiatorInfo_.toBuilder();
              }
              initiatorInfo_ = input.readMessage(cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(initiatorInfo_);
                initiatorInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              bindingKey_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              filebrowserVersion_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo.class, cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo.Builder.class);
    }

    public static final int INITIATOR_INFO_FIELD_NUMBER = 1;
    private cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo initiatorInfo_;
    /**
     * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
     */
    public boolean hasInitiatorInfo() {
      return initiatorInfo_ != null;
    }
    /**
     * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo getInitiatorInfo() {
      return initiatorInfo_ == null ? cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo.getDefaultInstance() : initiatorInfo_;
    }
    /**
     * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfoOrBuilder getInitiatorInfoOrBuilder() {
      return getInitiatorInfo();
    }

    public static final int BINDING_KEY_FIELD_NUMBER = 2;
    private volatile Object bindingKey_;
    /**
     * <code>optional string binding_key = 2;</code>
     */
    public String getBindingKey() {
      Object ref = bindingKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bindingKey_ = s;
        return s;
      }
    }
    /**
     * <code>optional string binding_key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBindingKeyBytes() {
      Object ref = bindingKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bindingKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILEBROWSER_VERSION_FIELD_NUMBER = 3;
    private volatile Object filebrowserVersion_;
    /**
     * <code>optional string filebrowser_version = 3;</code>
     */
    public String getFilebrowserVersion() {
      Object ref = filebrowserVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        filebrowserVersion_ = s;
        return s;
      }
    }
    /**
     * <code>optional string filebrowser_version = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFilebrowserVersionBytes() {
      Object ref = filebrowserVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        filebrowserVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (initiatorInfo_ != null) {
        output.writeMessage(1, getInitiatorInfo());
      }
      if (!getBindingKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bindingKey_);
      }
      if (!getFilebrowserVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, filebrowserVersion_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (initiatorInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getInitiatorInfo());
      }
      if (!getBindingKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bindingKey_);
      }
      if (!getFilebrowserVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, filebrowserVersion_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo)) {
        return super.equals(obj);
      }
      cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo other = (cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo) obj;

      boolean result = true;
      result = result && (hasInitiatorInfo() == other.hasInitiatorInfo());
      if (hasInitiatorInfo()) {
        result = result && getInitiatorInfo()
            .equals(other.getInitiatorInfo());
      }
      result = result && getBindingKey()
          .equals(other.getBindingKey());
      result = result && getFilebrowserVersion()
          .equals(other.getFilebrowserVersion());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasInitiatorInfo()) {
        hash = (37 * hash) + INITIATOR_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInitiatorInfo().hashCode();
      }
      hash = (37 * hash) + BINDING_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getBindingKey().hashCode();
      hash = (37 * hash) + FILEBROWSER_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getFilebrowserVersion().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 上报Initiator信息
     * </pre>
     *
     * Protobuf type {@code one2data.rbtmqmsgcli.initiator.ReportNodeInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:one2data.rbtmqmsgcli.initiator.ReportNodeInfo)
        cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo.class, cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo.Builder.class);
      }

      // Construct using cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (initiatorInfoBuilder_ == null) {
          initiatorInfo_ = null;
        } else {
          initiatorInfo_ = null;
          initiatorInfoBuilder_ = null;
        }
        bindingKey_ = "";

        filebrowserVersion_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfo_descriptor;
      }

      public cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo getDefaultInstanceForType() {
        return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo.getDefaultInstance();
      }

      public cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo build() {
        cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo buildPartial() {
        cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo result = new cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo(this);
        if (initiatorInfoBuilder_ == null) {
          result.initiatorInfo_ = initiatorInfo_;
        } else {
          result.initiatorInfo_ = initiatorInfoBuilder_.build();
        }
        result.bindingKey_ = bindingKey_;
        result.filebrowserVersion_ = filebrowserVersion_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo) {
          return mergeFrom((cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo other) {
        if (other == cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo.getDefaultInstance()) return this;
        if (other.hasInitiatorInfo()) {
          mergeInitiatorInfo(other.getInitiatorInfo());
        }
        if (!other.getBindingKey().isEmpty()) {
          bindingKey_ = other.bindingKey_;
          onChanged();
        }
        if (!other.getFilebrowserVersion().isEmpty()) {
          filebrowserVersion_ = other.filebrowserVersion_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo initiatorInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo, cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo.Builder, cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfoOrBuilder> initiatorInfoBuilder_;
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
       */
      public boolean hasInitiatorInfo() {
        return initiatorInfoBuilder_ != null || initiatorInfo_ != null;
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo getInitiatorInfo() {
        if (initiatorInfoBuilder_ == null) {
          return initiatorInfo_ == null ? cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo.getDefaultInstance() : initiatorInfo_;
        } else {
          return initiatorInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
       */
      public Builder setInitiatorInfo(cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo value) {
        if (initiatorInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          initiatorInfo_ = value;
          onChanged();
        } else {
          initiatorInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
       */
      public Builder setInitiatorInfo(
          cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo.Builder builderForValue) {
        if (initiatorInfoBuilder_ == null) {
          initiatorInfo_ = builderForValue.build();
          onChanged();
        } else {
          initiatorInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
       */
      public Builder mergeInitiatorInfo(cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo value) {
        if (initiatorInfoBuilder_ == null) {
          if (initiatorInfo_ != null) {
            initiatorInfo_ =
              cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo.newBuilder(initiatorInfo_).mergeFrom(value).buildPartial();
          } else {
            initiatorInfo_ = value;
          }
          onChanged();
        } else {
          initiatorInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
       */
      public Builder clearInitiatorInfo() {
        if (initiatorInfoBuilder_ == null) {
          initiatorInfo_ = null;
          onChanged();
        } else {
          initiatorInfo_ = null;
          initiatorInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo.Builder getInitiatorInfoBuilder() {
        
        onChanged();
        return getInitiatorInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfoOrBuilder getInitiatorInfoOrBuilder() {
        if (initiatorInfoBuilder_ != null) {
          return initiatorInfoBuilder_.getMessageOrBuilder();
        } else {
          return initiatorInfo_ == null ?
              cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo.getDefaultInstance() : initiatorInfo_;
        }
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.NodeBaseInfo initiator_info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo, cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo.Builder, cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfoOrBuilder> 
          getInitiatorInfoFieldBuilder() {
        if (initiatorInfoBuilder_ == null) {
          initiatorInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo, cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfo.Builder, cn.keptdata.one2data.header.message.protobuf.common.Node.NodeBaseInfoOrBuilder>(
                  getInitiatorInfo(),
                  getParentForChildren(),
                  isClean());
          initiatorInfo_ = null;
        }
        return initiatorInfoBuilder_;
      }

      private Object bindingKey_ = "";
      /**
       * <code>optional string binding_key = 2;</code>
       */
      public String getBindingKey() {
        Object ref = bindingKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          bindingKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string binding_key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBindingKeyBytes() {
        Object ref = bindingKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          bindingKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string binding_key = 2;</code>
       */
      public Builder setBindingKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bindingKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string binding_key = 2;</code>
       */
      public Builder clearBindingKey() {
        
        bindingKey_ = getDefaultInstance().getBindingKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string binding_key = 2;</code>
       */
      public Builder setBindingKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bindingKey_ = value;
        onChanged();
        return this;
      }

      private Object filebrowserVersion_ = "";
      /**
       * <code>optional string filebrowser_version = 3;</code>
       */
      public String getFilebrowserVersion() {
        Object ref = filebrowserVersion_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          filebrowserVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string filebrowser_version = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFilebrowserVersionBytes() {
        Object ref = filebrowserVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          filebrowserVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string filebrowser_version = 3;</code>
       */
      public Builder setFilebrowserVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filebrowserVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string filebrowser_version = 3;</code>
       */
      public Builder clearFilebrowserVersion() {
        
        filebrowserVersion_ = getDefaultInstance().getFilebrowserVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string filebrowser_version = 3;</code>
       */
      public Builder setFilebrowserVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filebrowserVersion_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:one2data.rbtmqmsgcli.initiator.ReportNodeInfo)
    }

    // @@protoc_insertion_point(class_scope:one2data.rbtmqmsgcli.initiator.ReportNodeInfo)
    private static final cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo();
    }

    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReportNodeInfo>
        PARSER = new com.google.protobuf.AbstractParser<ReportNodeInfo>() {
      public ReportNodeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReportNodeInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReportNodeInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReportNodeInfo> getParserForType() {
      return PARSER;
    }

    public cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReportNodeInfoAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:one2data.rbtmqmsgcli.initiator.ReportNodeInfoAck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    boolean hasBaseAck();
    /**
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck getBaseAck();
    /**
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder getBaseAckOrBuilder();
  }
  /**
   * Protobuf type {@code one2data.rbtmqmsgcli.initiator.ReportNodeInfoAck}
   */
  public  static final class ReportNodeInfoAck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:one2data.rbtmqmsgcli.initiator.ReportNodeInfoAck)
      ReportNodeInfoAckOrBuilder {
    // Use ReportNodeInfoAck.newBuilder() to construct.
    private ReportNodeInfoAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReportNodeInfoAck() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ReportNodeInfoAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder subBuilder = null;
              if (baseAck_ != null) {
                subBuilder = baseAck_.toBuilder();
              }
              baseAck_ = input.readMessage(cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseAck_);
                baseAck_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfoAck_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfoAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck.class, cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck.Builder.class);
    }

    public static final int BASE_ACK_FIELD_NUMBER = 1;
    private cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck baseAck_;
    /**
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    public boolean hasBaseAck() {
      return baseAck_ != null;
    }
    /**
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck getBaseAck() {
      return baseAck_ == null ? cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.getDefaultInstance() : baseAck_;
    }
    /**
     * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
     */
    public cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder getBaseAckOrBuilder() {
      return getBaseAck();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseAck_ != null) {
        output.writeMessage(1, getBaseAck());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseAck_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseAck());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck)) {
        return super.equals(obj);
      }
      cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck other = (cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck) obj;

      boolean result = true;
      result = result && (hasBaseAck() == other.hasBaseAck());
      if (hasBaseAck()) {
        result = result && getBaseAck()
            .equals(other.getBaseAck());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasBaseAck()) {
        hash = (37 * hash) + BASE_ACK_FIELD_NUMBER;
        hash = (53 * hash) + getBaseAck().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code one2data.rbtmqmsgcli.initiator.ReportNodeInfoAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:one2data.rbtmqmsgcli.initiator.ReportNodeInfoAck)
        cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfoAck_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfoAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck.class, cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck.Builder.class);
      }

      // Construct using cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (baseAckBuilder_ == null) {
          baseAck_ = null;
        } else {
          baseAck_ = null;
          baseAckBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfoAck_descriptor;
      }

      public cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck getDefaultInstanceForType() {
        return cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck.getDefaultInstance();
      }

      public cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck build() {
        cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck buildPartial() {
        cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck result = new cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck(this);
        if (baseAckBuilder_ == null) {
          result.baseAck_ = baseAck_;
        } else {
          result.baseAck_ = baseAckBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck) {
          return mergeFrom((cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck other) {
        if (other == cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck.getDefaultInstance()) return this;
        if (other.hasBaseAck()) {
          mergeBaseAck(other.getBaseAck());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck baseAck_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder> baseAckBuilder_;
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public boolean hasBaseAck() {
        return baseAckBuilder_ != null || baseAck_ != null;
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck getBaseAck() {
        if (baseAckBuilder_ == null) {
          return baseAck_ == null ? cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.getDefaultInstance() : baseAck_;
        } else {
          return baseAckBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public Builder setBaseAck(cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck value) {
        if (baseAckBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseAck_ = value;
          onChanged();
        } else {
          baseAckBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public Builder setBaseAck(
          cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder builderForValue) {
        if (baseAckBuilder_ == null) {
          baseAck_ = builderForValue.build();
          onChanged();
        } else {
          baseAckBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public Builder mergeBaseAck(cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck value) {
        if (baseAckBuilder_ == null) {
          if (baseAck_ != null) {
            baseAck_ =
              cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.newBuilder(baseAck_).mergeFrom(value).buildPartial();
          } else {
            baseAck_ = value;
          }
          onChanged();
        } else {
          baseAckBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public Builder clearBaseAck() {
        if (baseAckBuilder_ == null) {
          baseAck_ = null;
          onChanged();
        } else {
          baseAck_ = null;
          baseAckBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder getBaseAckBuilder() {
        
        onChanged();
        return getBaseAckFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      public cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder getBaseAckOrBuilder() {
        if (baseAckBuilder_ != null) {
          return baseAckBuilder_.getMessageOrBuilder();
        } else {
          return baseAck_ == null ?
              cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.getDefaultInstance() : baseAck_;
        }
      }
      /**
       * <code>optional .one2data.rbtmqmsgcli.common.BaseAck base_ack = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder> 
          getBaseAckFieldBuilder() {
        if (baseAckBuilder_ == null) {
          baseAckBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAck.Builder, cn.keptdata.one2data.header.message.protobuf.common.Common.BaseAckOrBuilder>(
                  getBaseAck(),
                  getParentForChildren(),
                  isClean());
          baseAck_ = null;
        }
        return baseAckBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:one2data.rbtmqmsgcli.initiator.ReportNodeInfoAck)
    }

    // @@protoc_insertion_point(class_scope:one2data.rbtmqmsgcli.initiator.ReportNodeInfoAck)
    private static final cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck();
    }

    public static cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReportNodeInfoAck>
        PARSER = new com.google.protobuf.AbstractParser<ReportNodeInfoAck>() {
      public ReportNodeInfoAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReportNodeInfoAck(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReportNodeInfoAck> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ReportNodeInfoAck> getParserForType() {
      return PARSER;
    }

    public cn.keptdata.one2data.header.message.protobuf.initiator.InitiatorMessage.ReportNodeInfoAck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfoAck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfoAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n initiator/InitiatorMessage.proto\022\036one2" +
      "data.rbtmqmsgcli.initiator\032\023common/Commo" +
      "n.proto\032\021common/Node.proto\"\205\001\n\016ReportNod" +
      "eInfo\022A\n\016initiator_info\030\001 \001(\0132).one2data" +
      ".rbtmqmsgcli.common.NodeBaseInfo\022\023\n\013bind" +
      "ing_key\030\002 \001(\t\022\033\n\023filebrowser_version\030\003 \001" +
      "(\t\"K\n\021ReportNodeInfoAck\0226\n\010base_ack\030\001 \001(" +
      "\0132$.one2data.rbtmqmsgcli.common.BaseAckB" +
      "J\n6cn.keptdata.one2data.header.message.p" +
      "rotobuf.initiatorB\020InitiatorMessageb\006pro",
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.keptdata.one2data.header.message.protobuf.common.Common.getDescriptor(),
          cn.keptdata.one2data.header.message.protobuf.common.Node.getDescriptor(),
        }, assigner);
    internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfo_descriptor,
        new String[] { "InitiatorInfo", "BindingKey", "FilebrowserVersion", });
    internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfoAck_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfoAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_one2data_rbtmqmsgcli_initiator_ReportNodeInfoAck_descriptor,
        new String[] { "BaseAck", });
    cn.keptdata.one2data.header.message.protobuf.common.Common.getDescriptor();
    cn.keptdata.one2data.header.message.protobuf.common.Node.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
