spring:
  # 数据库连接池配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.10.129:3306/ysj_develop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: T25lQDEyMzQ1Ng==

#  security:
#    user:
#      name: yushijie
#      password: 123456

server:
  port: 8081
